#!/bin/bash
#     repo-scripts is a set of scripts to work with your repository
#     Copyright (C) 2014 Evgeniy Alekseev
# 
#     This program is free software; you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation; either version 3 of the License, or
#     (at your option) any later version.
# 
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with this program; if not, see http://www.gnu.org/licenses
#     or write to the Free Software Foundation,Inc., 51 Franklin Street,
#     Fifth Floor, Boston, MA 02110-1301  USA


# functions
error_mes() {
  case "$1" in
    "config"    ) echo "[EE] Configuration file is not set"                   ;;
    "directory" ) echo "[EE] Directory does not exists"                       ;;
    "file"      ) echo "[EE] '$2' is a file"                                  ;;
    "flag"      ) echo "[EE] Unknown flag"                                    ;;
    "unknown"   ) echo "[EE] Unknown error"                                   ;;
  esac
  exit 1
}
func_help() {
  echo -e "Script written on BASH for update custom repository"
  echo -e "\nUsage: repo-update [ -c /etc/repo-scripts.conf ] [ -v | --version ] [ -h | --help ]"
  echo -e "\nParametrs:"
  echo -e "  -c               PATH     - path to configuration file. Default is
                              '/etc/repo-scripts.conf'"
  echo -e "\n  -v   --version            - show version and exit"
  echo -e "  -h   --help               - show this help and exit"
  exit 0
}
func_ver() {
  echo -e "                                   repo-update                                  "
  echo -e "A set of scripts to work with your repository                                   "
  echo -e "Version : 1.0.2                                                  License : GPLv3"
  echo -e "Author :                                             Evgeniy Alexeev aka arcanis"
  echo -e "E-mail :                                          esalexeev (at) gmail (dot) com"
  exit 0
}
func_remove() {
  DBNAME="$1"
  PKGNAME="$2"
  /usr/bin/repo-remove --quiet ${DBNAME}.db.tar.gz ${PKGNAME}
  /usr/bin/repo-remove --quiet ${DBNAME}.files.tar.gz ${PKGNAME}
  /usr/bin/rm -f ${PKGNAME}*
}
export -f func_remove
func_build() {
  PREPARE="$1"
  ROOT="$2"
  if grep "arch=('any')" PKGBUILD -q; then
    /usr/bin/sudo /usr/bin/staging-i686-build -r "${ROOT}"
  else
    if grep "lib32" PKGBUILD -q; then
      /usr/bin/sudo /usr/bin/staging-i686-build -r "${ROOT}"
      /usr/bin/sudo /usr/bin/multilib-staging-build -r "${ROOT}"
    else
      /usr/bin/sudo /usr/bin/staging-i686-build -r "${ROOT}"
      /usr/bin/sudo /usr/bin/staging-x86_64-build -r "${ROOT}"
    fi
  fi
  /usr/bin/cp *.pkg.tar.xz "${PREPARE}"
}
export -f func_build

CONF_FILE="/etc/repo-scripts.conf"
# parametrs parsing
until [ -z $1 ]; do
  case "$1" in
    "-h" | "--help"    ) func_help                                                    ;;
    "-v" | "--version" ) func_ver                                                     ;;
    "-c"               ) [ -z "$2" ] && error_mes "config" || CONF_FILE="$2" && shift ;;
    *                  ) error_mes "flag"                                             ;;
  esac
  shift
done
# default values
DBNAME="custom"
PREPAREDIR="${HOME}/arch/prepare"
REPODIR="${HOME}/arch/repo"
ROOTDIR="${HOME}/arch/root"
STAGINGDIR="${HOME}/arch/staging/"
USEGPG="yes"
echo "[II] Reading configuration from '${CONF_FILE}'"
. "${CONF_FILE}"
# variables

# error checking
if [ ! -d "${PREPAREDIR}" ]; then
  [ -e "${PREPAREDIR}" ] && error_mes "file" "${PREPAREDIR}"
  echo "[II] Creating directory '${PREPAREDIR}'"
  mkdir -p "${PREPAREDIR}" || error_mes "unknown"
fi
if [ ! -d "${REPODIR}" ]; then
  [ -e "${REPODIR}" ] && error_mes "file" "${REPODIR}"
  echo "[II] Creating directory '${REPODIR}'"
  mkdir -p "${REPODIR}/"{i686,x86_64} || error_mes "unknown"
fi
if [ ! -d "${REPODIR}/i686" ]; then
  [ -e "${REPODIR}/i686" ] && error_mes "file" "${REPODIR}/i686"
  echo "[II] Creating directory '${REPODIR}/i686'"
  mkdir -p "${REPODIR}/i686" || error_mes "unknown"
fi
if [ ! -d "${REPODIR}/x86_64" ]; then
  [ -e "${REPODIR}/x86_64" ] && error_mes "file" "${REPODIR}/x86_64"
  echo "[II] Creating directory '${REPODIR}/x86_64'"
  mkdir -p "${REPODIR}/x86_64" || error_mes "unknown"
fi
if [ ! -d "${STAGINGDIR}" ]; then
  [ -e "${STAGINGDIR}" ] && error_mes "file" "${STAGINGDIR}"
  echo "[II] Creating directory '${STAGINGDIR}'"
  mkdir -p "${STAGINGDIR}" || error_mes "unknown"
fi


## work block
# building
echo "[II] Building packages"
cd "${STAGINGDIR}"
/usr/bin/find -name 'PKGBUILD' -type f -execdir /usr/bin/bash -c "func_build "${PREPAREDIR}" "${ROOTDIR}"" \;

# signing
if [ ${USEGPG} == "yes" ]; then
  echo "[II] Signing"
  cd "${PREPAREDIR}"
  for PACKAGE in $(/usr/bin/find . -name '*.pkg.tar.xz'); do
    /usr/bin/gpg -b ${PACKAGE}
  done
fi

# creating packages list
cd "${PREPAREDIR}"
i686_PACKAGES=$(/usr/bin/find * -name '*-i686.pkg.tar.xz' -o -name "*-any.pkg.tar.xz")
x86_64_PACKAGES=$(/usr/bin/find * -name '*-x86_64.pkg.tar.xz' -o -name "*-any.pkg.tar.xz")
echo -n "[II] => i686 packages: \n${i686_PACKAGES}"
echo -n "[II] => x86_64 packages: \n${x86_64_PACKAGES}"

# updating i686 repo
echo "[II] Updating i686 repo"
cd "${REPODIR}/i686"
for PACKAGE in ${i686_PACKAGES}; do
  PKGNAME=$(echo ${PACKAGE} | /usr/bin/awk -F '-' '{for(i=1; i<=NF-3;i++) {printf("%s-", $i);}}' | /usr/bin/sed 's/.$//')
  /usr/bin/find -name "${PKGNAME}*.pkg.tar.xz" -type f -exec /usr/bin/bash -c "func_remove "${DBNAME}" "${PKGNAME}"" \;
  /usr/bin/cp "${PREPAREDIR}/${PACKAGE}" .
  [ ${USEGPG} == "yes" ] && /usr/bin/cp "${PREPAREDIR}/${PACKAGE}.sig" .
  /usr/bin/repo-add --new ${DBNAME}.db.tar.gz "${PACKAGE}"
  /usr/bin/repo-add --new --files ${DBNAME}.files.tar.gz "${PACKAGE}"
done

# updating x86_64 repo
echo "[II] Updating x86_64 repo"
cd "${REPODIR}/x86_64"
for PACKAGE in ${x86_64_PACKAGES}; do
  PKGNAME=$(echo ${PACKAGE} | /usr/bin/awk -F '-' '{for(i=1; i<=NF-3;i++) {printf("%s-", $i);}}' | /usr/bin/sed 's/.$//')
  /usr/bin/find -name "${PKGNAME}"'*.pkg.tar.xz' -type f -exec /usr/bin/bash -c "func_remove "${DBNAME}" "${PKGNAME}"" \;
  /usr/bin/cp "${PREPAREDIR}/${PACKAGE}" .
  [ ${USEGPG} == "yes" ] && /usr/bin/cp "${PREPAREDIR}/${PACKAGE}.sig" .
  /usr/bin/repo-add --new ${DBNAME}.db.tar.gz "${PACKAGE}"
  /usr/bin/repo-add --new --files ${DBNAME}.files.tar.gz "${PACKAGE}"
done

# clear
echo "[II] Clear"
cd "${PREPAREDIR}"
/usr/bin/rm -rf *
cd "${STAGINGDIR}"
/usr/bin/rm -rf *
